# -*- coding: utf-8 -*-
"""Project - 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r9cJ2j0clqDsewicQYMe4r5GTzjuEURf
"""

import warnings
warnings.filterwarnings("ignore")

!unzip /content/Project.zip

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import os
import shutil
import math
import imutils

ROOT_DIR = "/content/Brain Tumor Data Set/Brain Tumor Data Set"

num_of_images = {}

for dir in os.listdir(ROOT_DIR):
  num_of_images[dir] = len(os.listdir(os.path.join(ROOT_DIR, dir)))

num_of_images

if not os.path.exists("./train"):
  os.mkdir("./train")

  for dir in os.listdir(ROOT_DIR):
    os.makedirs("./train/"+dir)
    for img in np.random.choice(a=os.listdir(os.path.join(ROOT_DIR, dir) ) ,
                                size= (math.floor(70/100*num_of_images[dir])-5) , replace=False ):

      O = os.path.join(ROOT_DIR,dir,img)
      D = os.path.join('./train', dir)
      shutil.copy(O,D)
      os.remove(O)
else:
  print("Train Folder exists")

if not os.path.exists("./val"):
  os.mkdir("./val")

  for dir in os.listdir(ROOT_DIR):
    os.makedirs("./val/"+dir)
    for img in np.random.choice(a=os.listdir(os.path.join(ROOT_DIR, dir) ) ,
                                size= (math.floor(15/100*num_of_images[dir])-5) , replace=False ):

      O = os.path.join(ROOT_DIR,dir,img)
      D = os.path.join('./val', dir)
      shutil.copy(O,D)
      os.remove(O)
else:
  print("Train Folder exist")

if not os.path.exists("./test"):
  os.mkdir("./test")

  for dir in os.listdir(ROOT_DIR):
    os.makedirs("./test/"+dir)
    for img in np.random.choice(a=os.listdir(os.path.join(ROOT_DIR, dir) ) ,
                                size= (math.floor(15/100*num_of_images[dir])-5) , replace=False ):

      O = os.path.join(ROOT_DIR,dir,img)
      D = os.path.join('./test', dir)
      shutil.copy(O,D)
      os.remove(O)
else:
  print("Train Folder exist")

import numpy as np
import matplotlib.pyplot as plt
from keras.layers import Dense, Flatten
from keras.models import Model
from keras.applications.mobilenet import MobileNet, preprocess_input
from keras.preprocessing import image
import keras
from tensorflow.keras.preprocessing.image import ImageDataGenerator

base_model = MobileNet(input_shape=(224,224,3), include_top= False)

for layer in base_model.layers:
  layer.trainable = False

x = Flatten()(base_model.output)
x = Dense(units=2 , activation='sigmoid', name = 'predictions' )(x)

# creating our model.
model = Model(base_model.input, x)

model.summary()

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy']  )

train_datagen = ImageDataGenerator(
    zoom_range=0.2, shear_range=0.2, rescale=1./255, horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_data = train_datagen.flow_from_directory(directory= "/content/train",
                                               target_size=(224,224),
                                               batch_size=32,
                                  )

train_data.class_indices

val_data = val_datagen.flow_from_directory(directory= "/content/val",
                                           target_size=(224,224),
                                           batch_size=32,
                                  )

test_data = test_datagen.flow_from_directory(directory= "/content/test", target_size=(224,224), batch_size=32)

# to visualize the images in the traing data denerator

#t_img , label = train_data.next()
t_img, label = next(train_data)

# function when called will prot the images

def plotImages(img_arr, label):
  """
  input  :- images array
  output :- plots the images
  """

  for im, l in zip(img_arr,label) :
    plt.figure(figsize= (5,5))
    plt.imshow(im, cmap = 'gray')
    plt.title(im.shape)
    plt.axis = False
    plt.show()

# function call to plot the images
plotImages(t_img, label)

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# Define early stopping
es = EarlyStopping(
    monitor='val_accuracy',
    min_delta=0.01,
    patience=5,
    verbose=1,
    mode='auto'
)

# Define model checkpoint
mc = ModelCheckpoint(
    filepath='./best_model.keras',  # Ensure path is valid
    monitor='val_accuracy',
    verbose=1,
    save_best_only=True,
    mode='auto'
)

# Combine callbacks into a list
callbacks = [es, mc]

hist = model.fit(train_data,
                           steps_per_epoch= 10,
                           epochs= 30,
                           validation_data= val_data,
                           validation_steps= 16,
                           callbacks=[es,mc])

# Loading the best fit model
from keras.models import load_model
model = load_model("/content/best_model.keras")

h =  hist.history
h.keys()

plt.plot(h['accuracy'])
plt.plot(h['val_accuracy'] , c = "red")
plt.title("acc vs v-acc")
plt.show()

plt.plot(h['loss'])
plt.plot(h['val_loss'] , c = "red")
plt.title("loss vs v-loss")
plt.show()

# Evaluate the model
results = model.evaluate(test_data)  # Evaluate works directly with generators
accuracy = results[1]  # Assuming 'accuracy' is the second metric

print(f"The accuracy of your model is = {accuracy * 100:.2f} %")

path = "/content/Brain Tumor Data Set/Brain Tumor Data Set/Healthy/Not Cancer  (650).jpg"
img = image.load_img(path, target_size=(224,224) )

i = image.img_to_array(img)/255
input_arr = np.array([i])
input_arr.shape

pred = np.argmax(model.predict(input_arr))


if pred == 0:
  print("The MRI image is of BRAIN TUMOR")
else:
  print("The MRI image is of Healthey brain")


# to display the image
plt.imshow(input_arr[0])
plt.title("input image")
plt.show()

from keras.preprocessing import image

def get_img_array(img_path):
  """
  Input : Takes in image path as input
  Output : Gives out Pre-Processed image
  """
  path = img_path
  img = image.load_img(path, target_size=(224,224,3))
  img = image.img_to_array(img)
  img = np.expand_dims(img , axis= 0 )

  return img

import tensorflow as tf

# this function is udes to generate the heat map of aan image
def make_gradcam_heatmap(img_array, model, last_conv_layer_name, pred_index=None):
    # First, we create a model that maps the input image to the activations
    # of the last conv layer as well as the output predictions
    grad_model = tf.keras.models.Model(
        [model.inputs], [model.get_layer(last_conv_layer_name).output, model.output]
    )

    # Then, we compute the gradient of the top predicted class for our input image
    # with respect to the activations of the last conv layer
    with tf.GradientTape() as tape:
        last_conv_layer_output, preds = grad_model(img_array)
        if pred_index is None:
            pred_index = tf.argmax(preds[0])
        class_channel = preds[:, pred_index]

    # This is the gradient of the output neuron (top predicted or chosen)
    # with regard to the output feature map of the last conv layer
    grads = tape.gradient(class_channel, last_conv_layer_output)

    # This is a vector where each entry is the mean intensity of the gradient
    # over a specific feature map channel
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # We multiply each channel in the feature map array
    # by "how important this channel is" with regard to the top predicted class
    # then sum all the channels to obtain the heatmap class activation
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    # For visualization purpose, we will also normalize the heatmap between 0 & 1
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    return heatmap.numpy()

import matplotlib.cm as cm
from IPython.display import Image, display

def save_and_display_gradcam(img_path , heatmap, cam_path="cam.jpg", alpha=0.4):
    """
    img input shoud not be expanded
    """

    # Load the original image
    img = keras.preprocessing.image.load_img(img_path)
    img = keras.preprocessing.image.img_to_array(img)


    # Rescale heatmap to a range 0-255
    heatmap = np.uint8(255 * heatmap)

    # Use jet colormap to colorize heatmap
    jet = cm.get_cmap("jet")

    # Use RGB values of the colormap
    jet_colors = jet(np.arange(256))[:, :3]
    jet_heatmap = jet_colors[heatmap]

    # Create an image with RGB colorized heatmap
    jet_heatmap = keras.preprocessing.image.array_to_img(jet_heatmap)
    jet_heatmap = jet_heatmap.resize((img.shape[1], img.shape[0]))
    jet_heatmap = keras.preprocessing.image.img_to_array(jet_heatmap)

    # Superimpose the heatmap on original image
    superimposed_img = jet_heatmap * alpha + img
    superimposed_img = keras.preprocessing.image.array_to_img(superimposed_img)

    # Save the superimposed image
    superimposed_img.save(cam_path)

    # Display Grad CAM
    display(Image(cam_path))

# function that is used to predict the image type and the ares that are affected by covid


def image_prediction_and_visualization(path,last_conv_layer_name = "conv_pw_13", model = model):
  """
  input:  is the image path, name of last convolution layer , model name
  output : returs the predictions and the area that is effected
  """

  img_array = get_img_array(path)

  heatmap = make_gradcam_heatmap(img_array, model, last_conv_layer_name)

  plt.title("the heat map of the image is ")
  plt.imshow(heatmap)
  plt.show()

  pred = np.argmax(model.predict(img_array/255))
  print()
  print()
  print()
  if pred == 0:
    print("The MRI image is of BRAIN TUMOR")
  else:
    print("The MRI image is of Healthey brain")

  print()
  print()
  print()
  print("image with heatmap representing region on interest")

  # function call
  save_and_display_gradcam(path, heatmap)

  print()
  print("the original input image")
  print()

  a = plt.imread(path)
  plt.imshow(a, cmap = "gray")
  plt.title("Original image")
  plt.show()

#path:- provide any image from google or provide image from all image folder
path = "/content/val/Brain Tumor/Cancer (1083).JPG"
image_prediction_and_visualization(path)

# for normal image :  path:- provide any image from google or provide image from all image folder
path = "/content/Brain Tumor Data Set/Brain Tumor Data Set/Brain Tumor/Cancer (1973).jpg"

image_prediction_and_visualization(path)

# for a healthey brain mri, heap map will be none thus the x-ray will look blue